# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# Passed at https://github.com/2Alex20/Nazarov-java-pizzaproject/actions/runs/6513402834/job/17692949321

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 18 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          architecture: x64
      - name: Validate
        run: mvn validate
      - name: Test
        run: mvn test
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: xml test
        run: mvn -B package --file pom.xml
#  dependency not work
#      - name: Update dependency graph
#        uses: advanced-security/maven-dependency-submission-action@v1
# errors in the /home/runner/work/Nazarov-java-pizzaproject/Nazarov-java-pizzaproject/target/surefire-reports
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
